print("How old are you?", end=' ')
age = input()
print("How tall are you?", end=' ')
height = input()
print("How much do you weigh?", end=' ')
weight = input()
print(f"So, you are {age} old, {height} tall and {weight} heavy.")
print(type(weight))
canYouDo = input("What can you do?")
print(canYouDo + "\tHelloWorld")
